### ISSUE TITLE
UI issue of tags and action buttons

### ISSUE THREAD

**Issue by Frederick-S** [levlaz/braindump#113]
![2015-12-14 06 00 44](https://cloud.githubusercontent.com/assets/1182395/11769711/75e36c24-a228-11e5-806e-2bbf34481cd7.png)

It happens sometimes when I resize the browser.

**Comment by srisankethu** [comment]
Similar to issue #54

**Comment by levlaz** [comment]
@Frederick-S The UI has been redone, please let me know what you think!
