### ISSUE TITLE
Issues after Login

### ISSUE THREAD

**Issue by srisankethu** [levlaz/braindump#115]
1.The user is able to access auth/login after login

2.Adding auth/confirm to the address after login sends an email confirmation to the user

**Comment by levlaz** [comment]
I am not sure how much of a problem this really is -- there are no buttons that send someone to these places so there is no way to accidentally trigger this. 

You would have to intentionally go to these URLs to get this behavior and if someone is doing that -- then they are not using the app as it was intended to be used. There is only so much we can control so I don't think this is something worth fixing right now.
