### ISSUE TITLE
Add tooltips to action icons 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#119]
<img width="179" alt="screenshot 2015-12-13 23 07 33" src="https://cloud.githubusercontent.com/assets/7981032/11774841/586fe486-a1ee-11e5-94b4-fd58f5c67479.png">

**Comment by makalaaneesh** [comment]
Hey, I fixed it in this PR. #129

**Comment by levlaz** [comment]
Fixed, thanks so much @makalaaneesh
