### ISSUE TITLE
Have you considered packaging braindump for sandstorm?

### ISSUE THREAD

**Issue by ovizii** [levlaz/braindump#127]
Here is the link incase you haven't heard about it, tis a very interesting project and braindump might be a perfect fit: https://sandstorm.io/ 

P.S. I'm just a very happy sandstorm user and happened to stumble upon your project and liked it very much so I thought I'd ask :-)

**Comment by levlaz** [comment]
Hi @ovizii I love sandstorm :) Its an awesome project. 

I think I would love to package something up as soon as I have a release that is "stable" -- briandump is less than a month old and I would like to get to at least a "real" beta before I consider making packages for it.

**Comment by ovizii** [comment]
oh, wow, I didn't realize the project is this new. 
Good luck then, looks nice from what I can see so far.

**Comment by levlaz** [comment]
Thanks @ovizii hope to have an official release soon :)
