### ISSUE TITLE
The side-bar css needs changes

### ISSUE THREAD

**Issue by makalaaneesh** [levlaz/braindump#132]
![screenshot from 2015-12-16 10 46 37](https://cloud.githubusercontent.com/assets/6829754/11832797/7c344092-a3e2-11e5-9e8d-a7629dd0bbb2.png)

The css needs to be refactored.
1) The sidebar should be fixed (no scrolling)
2) If possible, the height of the```li``` element should be dynamically set according to the number of elements in the sidebar

**Comment by levlaz** [comment]
What is your resolution?

**Comment by makalaaneesh** [comment]
1366x768

**Comment by levlaz** [comment]
Thanks, I really need to test this on different resolutions :)

**Comment by levlaz** [comment]
This has been fixed.
