### ISSUE TITLE
Vagrant Issue

### ISSUE THREAD

**Issue by dfdx2** [levlaz/braindump#146]
When doing `vagrant up`  I get the error message
    Vagrant:
    `*Unknown configuration section 'memory='`

**Comment by levlaz** [comment]
@dfdx2 I just updated the Vagrantfile, can you try again?

**Comment by dfdx2** [comment]
I received a new error this time
`There are errors in the configuration of this machine`
`Please fix the following errors and try again`
`vm:`
`*The following settings shouldn't exist: memory`

**Comment by levlaz** [comment]
Can you tell me which version of Vagrant you are using along with the OS and the version of Virtualbox?

**Comment by levlaz** [comment]
@dfdx2 nevermind, I had the same issue it was an error in the config. Should work now!
