### ISSUE TITLE
Help menu for markup symbols

### ISSUE THREAD

**Issue by RebekahAimee** [levlaz/braindump#147]
As far as I can tell, there's no list of markup commands available to the user. We need a page or a popup menu or something that will list and give examples of them.

Admittedly, a WYSIWYG editor would possibly be better--something like the post writing interface in WordPress, for example--but both options would probably be just fine and this is maybe faster to implement.

I think both should be coded at some point and a toggle option put into the Settings form, personally.

**Comment by levlaz** [comment]
This will help with https://github.com/levlaz/braindump/issues/7

**Comment by levlaz** [comment]
[ProseMirror](https://prosemirror.net/ which is now in use in Braindump is both a WYSIWIG and markdown editor. It addresses the best of both worlds. I think this is now addressed.
