### ISSUE TITLE
TODO is not deleted when note is deleted 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#167]
If you delete a note with TODO items the TODO items remain.

**Comment by makalaaneesh** [comment]
@levlaz  I was a bit unsure about this. The ```cascade="all, delete-orphan"``` should do it right?

**Comment by levlaz** [comment]
Yes that should work!

This should only happen when the note is "deleted forever" otherwise you may accidentally remove TODOs if the note is deleted by mistake. :) 

Best, 
Lev
