### ISSUE TITLE
"You denied the request to sign in."

### ISSUE THREAD

**Issue by iamgroot42** [levlaz/braindump#175]
This message is flashed when I try logging in via Github. A bug,I guess.

**Comment by levlaz** [comment]
I get the same error :( 

I am not 100% sure what is wrong, but I wonder if it has to do with the fact that the GitHub email I am using is the same as my account briandump. Is this also true for you?

**Comment by iamgroot42** [comment]
It is the same email-id, yes.

**Comment by bambooom** [comment]
same error here......

**Comment by t-boom** [comment]
Same here
