### ISSUE TITLE
Instruction on TODO tab

### ISSUE THREAD

**Issue by bambooom** [levlaz/braindump#180]
Maybe an instruction on how to add TODOs should display on TODO tab because I didn't know how to add TODO items until I tried to add note using GFM ` - [ ] item1`......
Or maybe can have the feature that adding TODO items directly in TODO tab?

**Comment by levlaz** [comment]
Right now it only shows TODOs that come from a note using GFM todo lists. 

I think it would be great to be able to add a TODO from the TODO view and then also be able to add a note later perhaps. 

In any case, I agree documentation is needed for many parts of the app.
