### ISSUE TITLE
TODO items are not saved when checked off in the UI

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#19]
If a user checks off a TODO item in the UI it is not saved in the DB

**Comment by makalaaneesh** [comment]
@levlaz Hey, I'm working on this issue :) The ```marked.js```  does not support a TODO-list update. I'm working on a javascript workaround.

**Comment by levlaz** [comment]
It does not, what I am thinking is that we set up an ajax endpoint (maybe via the API) and just call it when the button is clicked.

**Comment by levlaz** [comment]
Also, I want TODOs to be special, they should have their own DB model and be able to be tracked independently from a note (should be linked to a note via a Foreign Key though).

**Comment by makalaaneesh** [comment]
Yup, exactly. I was working on the ajax right now.
And, ok! I will make a separate model :+1:

**Comment by levlaz** [comment]
@makalaaneesh awesome, you rock ! :D

**Comment by levlaz** [comment]
In my mind the model is just: 

Todo { 
id
title 
note_id(FK)
created_date
updated_date
closed_date
}

**Comment by makalaaneesh** [comment]
@levlaz :D Yup. I think this model structure will suffice. One thing though.
Can we assume that a note will not have duplicate TODO-items?
If not, I will have to add an ```id``` attribute to the each ``` <li> ``` element  before saving it to the DB

**Comment by makalaaneesh** [comment]
@levlaz I sent a PR :) #137
