### ISSUE TITLE
"Dump Your Brain:" textarea doesn't allow for spellcheck

### ISSUE THREAD

**Issue by felicianotech** [levlaz/braindump#211]
When creating a note (and presumably editing), the "Dump Your Brain:" section doesn't trigger Google Chrome to spellcheck the text.

As someone who misspells things hourly, this issue really hurts my productivity by having to re-read my notes several times more than normal.

A built-in spell checker could be an alternate or additional solution.

**Comment by levlaz** [comment]
As much as I hate +1 

+1

**Comment by felicianotech** [comment]
This was fixed with the new editor.
