### ISSUE TITLE
List of Notes Don't Have an Obvious Order

### ISSUE THREAD

**Issue by felicianotech** [levlaz/braindump#212]
When you choose a notebook and all of it's notes are display, they don't seem to be in order. I would assume they would be sorted by last modified, or alphabetically but I can't determine why they are in the order they are. Nor is there any sorting options.
![https___braindump](https://cloud.githubusercontent.com/assets/6017470/12932982/9615c2a0-cf3a-11e5-8563-9aeeb8fbb6c4.png)

**Comment by levlaz** [comment]
@felicianotech The current order is: 

1. Last Modified 
2. Favorites First 

So you will see your favorites by last modified date and then all others. 

The note order is defined here: https://github.com/levlaz/braindump/blob/master/app/main/views.py#L17


```
        notes = Note.query.filter_by(
            author_id=current_user.id,
            is_deleted=False).order_by(
            Note.is_favorite.desc(),
            Note.updated_date.desc()).all()
```

I agree sorting should be an option. 

Do you think the default order makes sense?

**Comment by levlaz** [comment]
@felicianotech fml -- I just noticed you said 

>When you choose a notebook and all of it's notes are display

That logic is actually not the same. I think it should be consistent. 

1. Favorites First 
2. Last Modified Date 

Would you agree?

**Comment by felicianotech** [comment]
That works if:

1. Favorites are visually identified as different (could also be pinned since favoriting a note?)
2. Last modified is reverse chronological.

Why I opened this issue however is that I don't have any favorites. That's (in the screenshot) just how it's being displayed.
