### ISSUE TITLE
Latest Docker Image isn't tagged latest

### ISSUE THREAD

**Issue by felicianotech** [levlaz/braindump#214]
This may be on purpose, and this may not be the right place to put this but....

`docker pull` assumes the tag latest when not specific. That tag doesn't exists in levlaz/braindump so it fails :(

I believe you can take the most recent image twice. Once with the version number and again to apply latest.

**Comment by levlaz** [comment]
Thanks @felicianotech this has now been fixed. Also I am now using Quay.io instead of Dockerhub so you can get the latest image with `docker pull quay.io/levlaz/braindump`
