### ISSUE TITLE
Can't view notes from notebook view

### ISSUE THREAD

**Issue by drazisil** [levlaz/braindump#264]
When I click on notebooks, it shows notes on the left, but no note content. I can only see note content when clicking on home.

This is confusing and unhelpful.

I am on mobile android if that matters.

**Comment by levlaz** [comment]
Thanks for the bug report, the entire mobile view is broken right now :(

**Comment by levlaz** [comment]
Almost done, will track here: https://github.com/levlaz/braindump/issues/291
