### ISSUE TITLE
Shared Notes View does not link to Note

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#302]
![shared notes bug](https://cloud.githubusercontent.com/assets/7981032/20261826/63e08882-aa14-11e6-8394-191bb827daf6.png)

**Comment by dtrebbien** [comment]
Don't you also need to change this:

<code>
{{current_user.notes.filter_by(id=shared_note.id).first().title}}
</code>

to:

<code>
{{current_user.notes.filter_by(id=shared_note.**note_**id).first().title}} 
</code>

**Comment by levlaz** [comment]
@dtrebbien Thanks! You are absolutely right, I did catch it later. Thanks for the comment. :)
