### ISSUE TITLE
Speed up Vagrant provisioning

### ISSUE THREAD

**Issue by felicianotech** [levlaz/braindump#316]
When and if #315 is merged, bootstrap.sh and Vagrantfile can be improved in a few ways.

1) Add all of the repositories and GPG keys first, then run `apt-get update`. This will reduce the number of times you need to run this from about 3 to just 1, speeding up install.

2) Allow `bootstrap.sh` to read an 'env' as a variable. Then, have this apply to running in Vagrant as well as CircleCI. This way you don't need to duplicate as many commands between `bootstrap.sh` and CircleCI. Change a command in one place and it will apply to both environments.

3) Install NodeJS via their repository, so you need NVM installed as well.

4) Allow to Vagrantfile to use Docker as a target as well. This way users can run BrainDump locally in containers. This is not only lighter weight, but mimics products even closer than VirtualBox would.

**Comment by levlaz** [comment]
@felicianotech I merged 315, I actually have been developing in virtualenv locally and not using Vagrant at all. Please feel free to update all of the vagrant related stuff as you see fit.

**Comment by felicianotech** [comment]
Ah okay. I rather not waste my time then. Thanks.
