### ISSUE TITLE
Confirmation Page Shouldn't Warn You That You Didn't Sign In

### ISSUE THREAD

**Issue by felicianotech** [levlaz/braindump#34]
When clicking the confirmation link (from the confirmation email), the yellow banner comes up saying you need to be signed in to access this page.

That's kind of implied due to the process of registering in the first place.

**Comment by srisankethu** [comment]
Refer to Pull request #111

**Comment by levlaz** [comment]
Fixed in https://github.com/levlaz/braindump/pull/111
