### ISSUE TITLE
Settings View 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#44]
User should be able to: 

* View App Settings 
* Change Email 
* Change Password

**Comment by srisankethu** [comment]
What do you mean by view app settings?

**Comment by levlaz** [comment]
Its a placeholder for settings that will come in the future, for instance there will be a calendar integration and users will be able to add their creds here. 

The will also be able to generate and view their API key in the app settings view as well.

**Comment by levlaz** [comment]
I am now working on this.
