### ISSUE TITLE
Firefox: CSS issue with Known Issues list on homepage

### ISSUE THREAD

**Issue by ctidd** [levlaz/braindump#49]
Hi,

There's currently a Firefox-specific issue with the h5 elements nested inside links in the homepage's Known Issues list.

The combination of nested elements with the given display properties is resulting in a glitch where each list item is rendered as though there's a line break after its bullet, before the h5 text begins.

**Suggested fixes:**
Remove the h5 elements *or* add `.bug-title { display: inline-block; }`.

**Notes:**
Seen on Firefox latest on OS X.
This currently displays as intended on Chrome and Safari.
I haven't checked any IE versions.

Nice project!

**Comment by levlaz** [comment]
@ctidd Thanks so much for letting me know! I need to get out of the habit of only looking at my app in one browser. :)
