### ISSUE TITLE
GitHub Flavored Markdown 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#5]
For the love of God.

**Comment by MikeyYeahYeah** [comment]
Would love to see Github Markdown.  In particular, looking forward to the checkbox function.

- [ ]
- [x]

**Comment by levlaz** [comment]
This seems like the best bet https://github.com/chjj/marked

**Comment by akerl** [comment]
+1 on this.

Typing in multiline (like a list) and having it come back as a block is </3, being able to reuse all the github markdown I've drilled into my brain would rock

**Comment by levlaz** [comment]
You asked we listened. GFM is now fully supported (except for lists :( @MikeyYeahYeah )

**Comment by levlaz** [comment]
Im using [this library](https://github.com/chjj/marked/issues/107) and someone made a PR for lists but it was not merged, I may pull it in manually because I would find lists super useful as well. :)
