### ISSUE TITLE
UI overflow when tons of tags 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#54]
<img width="257" alt="screenshot 2015-12-06 23 41 15" src="https://cloud.githubusercontent.com/assets/7981032/11619183/e545f17e-9c72-11e5-8d56-ffb9ab82a8b0.png">

**Comment by Static-Flow** [comment]
I just committed a change for this, let me know if it solves it. I also have a suggestion for the note divs themselves.

**Comment by levlaz** [comment]
The UI Has been redone, would love some feedback. I think the "card" model was not as good as the current model.
