### ISSUE TITLE
Form Title is not validated 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#56]
DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.DataError) value too long for type character varying(200)

**Comment by iamgroot42** [comment]
Created a PR to fix the same : https://github.com/levlaz/braindump/pull/92

**Comment by levlaz** [comment]
Fixed in https://github.com/levlaz/braindump/pull/92
