### ISSUE TITLE
Footer doesn't show up if logged in

### ISSUE THREAD

**Issue by akerl** [levlaz/braindump#6]
Was looking for github/bugs link, but it vanished when I logged in

**Comment by levlaz** [comment]
I did that intentionally for now because this is a fake SPA.. do you think it makes sense to include it? :)

**Comment by akerl** [comment]
Not sure. I guess the important one is having a "file bugs here" link somewhere on the page after login; I keep manually hunting for this page :)

**Comment by levlaz** [comment]
It does not help that you actually can't see the home page if you are not logged in :) Thanks for the feedback, you are my hero.
