### ISSUE TITLE
UI Enhancements 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#74]
Someone put this on the demo board but I think they are both great ideas. :) 

>Some personal tips from a programmer without any design qualification:
>    -- I think you should better align your UI elements so they spread in a even way.
>    -- For example, giving margin-right:30px to the note-action buttons makes them look way better
>    -- The date on the top should be centered(vertical). Also, is the date more important than the title should you not place the date elsewhere and put the title there?

**Comment by alexfornuto** [comment]
I think that this might be related; the mobile view is blank after logging in.
![screenshot_20151209-095805](https://cloud.githubusercontent.com/assets/2349184/11691636/e60709ba-9e69-11e5-9ffb-43a01c4529b3.png)

**Comment by levlaz** [comment]
I think that's because you don't have any notes. :) 

In any case the mobile UI is completely broken right now.

**Comment by alexfornuto** [comment]
You're right, at the time I didn't. I had signed up from my phone.

**Comment by levlaz** [comment]
I am sorry for the horribe mobile experience, I hope to have an update this weekend that makes it usable. :)

**Comment by alexfornuto** [comment]
No worries. Did you need to save the other notes from this issue before closing?

**Comment by levlaz** [comment]
Nope I think I did everything that I agreed with, will make more specific issues for other stuff. Mobile will be tracked here https://github.com/levlaz/braindump/issues/39 <https://github.com/levlaz/braindump/issues/39>
