### ISSUE TITLE
Options in drop-down menu (for account options) are of same color as background

### ISSUE THREAD

**Issue by iamgroot42** [levlaz/braindump#78]
![image](https://cloud.githubusercontent.com/assets/10141323/11653116/d58f635a-9dc1-11e5-9fe5-a857c6daa6ae.png)

Can be fixed by using some different color for the text.

**Comment by levlaz** [comment]
This is an artifact from the first UI -- this whole thing is going to be redone in https://github.com/levlaz/braindump/issues/44

**Comment by iamgroot42** [comment]
Redirect to https://github.com/levlaz/braindump/issues/44
