### ISSUE TITLE
Oauth Login

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#97]
Using [Flask Oauthlib](https://flask-oauthlib.readthedocs.org/en/latest/)

* Twitter 
* GitHub 
* Google

**Comment by acemaster** [comment]
@levlaz I would like to implement this feature. Is this issue taken ?

**Comment by levlaz** [comment]
@acemaster It is not, please feel free to work on it! This is something that should go into the auth module. :)

**Comment by acemaster** [comment]
@levlaz Cool :+1: I will post regarding the progress I am making

**Comment by levlaz** [comment]
Thank you very much!

**Comment by acemaster** [comment]
@levlaz I had a few doubts
1. For which all services do you want login, like Google, Facebook, Github etc.
2. Once logged in with oauth the user has to added in the db right. Should I use the existing model or create a new one? 

Currently I am using keys from a test application I created on Google and Github.
