### ISSUE TITLE
Account dropdown menu items are invisible in "auth/unconfirmed" page

### ISSUE THREAD

**Issue by Frederick-S** [levlaz/braindump#98]
Font color and background color are both white, so we cannot see it.

![untitled](https://cloud.githubusercontent.com/assets/1182395/11704179/4c0f7376-9f20-11e5-8500-b8db91f1fb0f.png)

**Comment by iamgroot42** [comment]
Going to be redone in https://github.com/levlaz/braindump/issues/44

**Comment by levlaz** [comment]
@Frederick-S Thanks for letting us know, as @iamgroot42 mentioned this will be fixed soon!
