### ISSUE TITLE
[RFC] reCaptcha instead of email-validation

### ISSUE THREAD

**Issue by iamgroot42** [levlaz/braindump#99]
Instead of using email validation, reCaptcha can be used ( in addition to oAuth via Gmail, Facebook or others).

**Comment by levlaz** [comment]
I am not a huge fan of reCaptcha :( 

I agree email is annoying but its a one time thing and once oAuth is around it will be optional.

**Comment by levlaz** [comment]
Closing this unless someone has other comments. I think Oauth is the way to go, and then email confirmation for people who want to use email.
